import Head from "next/head";
import Featured from "../components/Featured";
import CakeList from "../components/CakeList"

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />
      <CakeList />
    </div>
  );
}
